"""empty message

Revision ID: 767b03dc459f
Revises: dd9427fd9243
Create Date: 2024-10-03 22:22:03.465536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767b03dc459f'
down_revision = 'dd9427fd9243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('text')

    with op.batch_alter_table('park', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('park', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
